<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Gpsd-dev] xgps - AttributeError: dictwrapper instance has no	attribute 'lat'
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/gpsd-dev/2010-October/index.html" >
   <LINK REL="made" HREF="mailto:gpsd-dev%40lists.berlios.de?Subject=Re%3A%20%5BGpsd-dev%5D%20xgps%20-%20AttributeError%3A%20dictwrapper%20instance%20has%20no%0A%09attribute%20%27lat%27&In-Reply-To=%3C4CC1C845.6070500%40bzed.de%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="008210.html">
   <LINK REL="Next"  HREF="008212.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Gpsd-dev] xgps - AttributeError: dictwrapper instance has no	attribute 'lat'</H1>
    <B>Bernd Zeimetz</B> 
    <A HREF="mailto:gpsd-dev%40lists.berlios.de?Subject=Re%3A%20%5BGpsd-dev%5D%20xgps%20-%20AttributeError%3A%20dictwrapper%20instance%20has%20no%0A%09attribute%20%27lat%27&In-Reply-To=%3C4CC1C845.6070500%40bzed.de%3E"
       TITLE="[Gpsd-dev] xgps - AttributeError: dictwrapper instance has no	attribute 'lat'">bernd at bzed.de
       </A><BR>
    <I>Fri Oct 22 19:22:13 CEST 2010</I>
    <P><UL>
        <LI>Previous message: <A HREF="008210.html">[Gpsd-dev] (New) device with linux...
</A></li>
        <LI>Next message: <A HREF="008212.html">[Gpsd-dev] Symmetricom 58534A &quot;Timing Antenna&quot; GPS receiver
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#8211">[ date ]</a>
              <a href="thread.html#8211">[ thread ]</a>
              <a href="subject.html#8211">[ subject ]</a>
              <a href="author.html#8211">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hi,

just to document it - when running
gpsfake gpsd/test/daemon/ch-4701.log
I (more or less reproducible) managed to run into the following backtrace in xgps:

poll: data is
'{&quot;class&quot;:&quot;TPV&quot;,&quot;tag&quot;:&quot;GSA&quot;,&quot;device&quot;:&quot;/dev/pts/0&quot;,&quot;epv&quot;:0.000,&quot;mode&quot;:3}\r\n'
Traceback (most recent call last):
  File &quot;./xgps&quot;, line 670, in handle_response
    self.update_gpsdata(self.daemon.data)
  File &quot;./xgps&quot;, line 624, in update_gpsdata
    widget.set_text(hook(self, tpv))
  File &quot;./xgps&quot;, line 356, in &lt;lambda&gt;
    (&quot;Latitude&quot;, lambda s, r: s.update_latitude(r)),
  File &quot;./xgps&quot;, line 550, in update_latitude
    lat = gps.clienthelpers.deg_to_str(self.deg_type, abs(data.lat))
AttributeError: dictwrapper instance has no attribute 'lat'

I don't have the time to debug that yet...

Cheers,

Bernd
-- 
 Bernd Zeimetz                            Debian GNU/Linux Developer
 <A HREF="http://bzed.de">http://bzed.de</A>                                <A HREF="http://www.debian.org">http://www.debian.org</A>
 GPG Fingerprint: ECA1 E3F2 8E11 2432 D485  DD95 EB36 171A 6FF9 435F

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="008210.html">[Gpsd-dev] (New) device with linux...
</A></li>
	<LI>Next message: <A HREF="008212.html">[Gpsd-dev] Symmetricom 58534A &quot;Timing Antenna&quot; GPS receiver
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#8211">[ date ]</a>
              <a href="thread.html#8211">[ thread ]</a>
              <a href="subject.html#8211">[ subject ]</a>
              <a href="author.html#8211">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/gpsd-dev">More information about the Gpsd-dev
mailing list</a><br>
</body></html>
